# Generated by Django 3.2.20 on 2023-09-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_auto_20230917_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
